### ISSUE TITLE
Loosen requirements

### ISSUE THREAD

**Issue by timvink** [raeslab/lorepy#4]
The requirements.txt looks like the result of a `pip freeze`.

Can we instead only specify the high level dependencies, and only specify the minimum version.
This would improve compatibility with other environments a lot (I don't want to downgrade my scikit-learn version to use this package).

If you're worried about breaking upstream changes, it's possible to schedule unit tests to run weekly.

**Comment by sepro** [comment]
This might have been me goofing again. The requirements.txt is indeed a freeze of the environment I was using while developing. 

I (perhaps mistakenly) assumed versions defined in setup.py would specify acceptable versions of dependencies. If requirements.txt is messing with that it indeed needs to be adjusted.

**Comment by timvink** [comment]
Yes, no need to pin specific versions. Will you update or do you want me to make a PR?

**Comment by sepro** [comment]
Actually there is a reason behind pinning those versions. Developing with
the oldest dependencies specified in setup.py has been my way to ensure
compatibility with those and letting GitHub actions on push/weekly check
the latest (and reasonably ensuring everything in between would work).
Never caused any issues as I keep a separate vent for each project/package.

In case there is a PR that is also what I'll use to test.

Would require an additional action that specifically would test backwards
compatibility with older version of dependencies. (And even then I think I
prefer to get that error during development 😕)

I understand this comes at a minor inconvenience if someone wants to add
missing packages to an existing vent.

**Comment by timvink** [comment]
Have a look at commonly used python packages. They don't pin exact versions. Have you used lorepy in an ML project? If all packages would pin dependencies, you would get many conflicts.

You could use uv to install the oldest available dependencies (https://github.com/astral-sh/uv) in a GitHub actions job, if you're concerned about compatibility. And another scheduled weekly job if you're worried about updates in dependencies breaking lorepy.

The correct approach of pinned reqs basically means we can't use it, I hope you reconsider.

**Comment by sepro** [comment]
Will check on Monday. Pip should only care about setup .py according to the docs when installing (and hence I haven't encountered issues). However as you mention uv, that might not be universally true and I'm happy to reconsider. (I just found out uv existed yesterday)

`important to be clear that pip determines package dependencies using [install_requires metadata](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html), not by discovering requirements.txt files embedded in projects.`

Keeping those minimal required version in setup.py correctly defined is something I do care about.

**Comment by sepro** [comment]
There actually is a mismatch between the requirements.txt and setup.py so right now it isn't quite doing what it needs to. So will definitely need to change something

**Comment by timvink** [comment]
Ohhh I didn't read that right! 🙈 

I thought requirements.txt was imported in setup.py, which is the pattern I have seen most often. Sorry about that.
